export const actionTypes = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_ERROR: 'LOGIN_ERROR',

  REGISTER_REQUEST: 'REGISTER_REQUEST',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_ERROR: 'REGISTER_ERROR',

  GET_ALL_PLANS_REQUEST: 'GET_ALL_PLANS_REQUEST',
  GET_ALL_PLANS_SUCCESS: 'GET_ALL_PLANS_SUCCESS',
  GET_ALL_PLANS_ERROR: 'GET_ALL_PLANS_ERROR',

  GET_PLAN_DETAILS_REQUEST: 'GET_PLAN_DETAILS_REQUEST',
  GET_PLAN_DETAILS_SUCCESS: 'GET_PLAN_DETAILS_SUCCESS',
  GET_PLAN_DETAILS_ERROR: 'GET_PLAN_DETAILS_ERROR',

  ADD_PLAN_REQUEST: 'ADD_PLAN_REQUEST',
  ADD_PLAN_SUCCESS: 'ADD_PLAN_SUCCESS',
  ADD_PLAN_ERROR: 'ADD_PLAN_ERROR',

  UPDATE_PLAN_REQUEST: 'UPDATE_PLAN_REQUEST',
  UPDATE_PLAN_SUCCESS: 'UPDATE_PLAN_SUCCESS',
  UPDATE_PLAN_ERROR: 'UPDATE_PLAN_ERROR',

  DELETE_PLAN_REQUEST: 'DELETE_PLAN_REQUEST',
  DELETE_PLAN_SUCCESS: 'DELETE_PLAN_SUCCESS',
  DELETE_PLAN_ERROR: 'DELETE_PLAN_ERROR',

  DELETE_MULTIPLE_PLANS_REQUEST: 'DELETE_MULTIPLE_PLANS_REQUEST',
  DELETE_MULTIPLE_PLANS_SUCCESS: 'DELETE_MULTIPLE_PLANS_SUCCESS',
  DELETE_MULTIPLE_PLANS_ERROR: 'DELETE_MULTIPLE_PLANS_ERROR',
};
