POST https://myplanr.netlify.app/.netlify/functions/server/login
Content-Type: application/json

{
  "username": "nagesh",
  "password": "pass"
}
###

POST http://192.168.0.103:7000/token
Content-Type: application/json

{"token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5hZ2VzaCIsImlkIjoiMyIsImlhdCI6MTYxNDg0NTMwOX0.UuaC4MOLAdbslshphgyDIp9_FeE-vJFcOtNcKVmtZQc"}

###

GET https://myplanr.netlify.app/.netlify/functions/server/tasks
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.bmFnZXNo.QtXV5ZMUo5aCCdlHwU4nCBawY5_2Mkb-5bAlz769CxA

###

POST http://192.168.0.103:7000/login
Content-Type: application/json

{
  "username": "nagesh",
  "password": "pass"
}

###

POST http://192.168.0.103:7000/token
Content-Type: application/json

{"token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5hZ2VzaCIsImlkIjoiMyIsImlhdCI6MTYxNDg0NTMwOX0.UuaC4MOLAdbslshphgyDIp9_FeE-vJFcOtNcKVmtZQc"}

###

GET http://192.168.0.103:7000/tasks
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.bmFnZXNo.QtXV5ZMUo5aCCdlHwU4nCBawY5_2Mkb-5bAlz769CxA

###

POST http://192.168.0.103:7000/tasks
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.bmFnZXNo.QtXV5ZMUo5aCCdlHwU4nCBawY5_2Mkb-5bAlz769CxA

{
  "title": "Learn React",
  "description": "Nothing",
  "targetDate": "2021-03-28"
}

###