POST http://localhost:7000/login
Content-Type: application/json

{
  "username": "nagesh",
  "id": "3"
}

###

POST http://localhost:7000/token
Content-Type: application/json

{"token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5hZ2VzaCIsImlkIjoiMyIsImlhdCI6MTYxNDg0NTMwOX0.UuaC4MOLAdbslshphgyDIp9_FeE-vJFcOtNcKVmtZQc"}

###

GET http://localhost:7000/tasks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5hZ2VzaCIsImlkIjoiMyIsImlhdCI6MTYxNjIzMjk5MywiZXhwIjoxNjE2MjMzMjkzfQ.2wPEphbjOuUV7sEKl0S1CxjimI8dIdhfUwZQoJuHRtM