POST https://myplanr.netlify.app/.netlify/functions/server/login
Content-Type: application/json

{
  "username": "nagesh",
  "password": "pass"
}
###

GET https://myplanr.netlify.app/.netlify/functions/server/tasks
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.bmFnZXNo.QtXV5ZMUo5aCCdlHwU4nCBawY5_2Mkb-5bAlz769CxA

###

POST http://192.168.0.101:7000/login
Content-Type: application/json

{
  "username": "nageshwar521",
  "password": "pass"
}

###

GET http://192.168.0.101:7000/tasks
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.bmFnZXNo.QtXV5ZMUo5aCCdlHwU4nCBawY5_2Mkb-5bAlz769CxA

###

POST http://192.168.0.101:7000/tasks
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.bmFnZXNod2FyNTIx.SB5nAlANau9o8F0bfvlAnlwViEIggiRtimFm4FOkBAU
Content-Type: application/json

{
  "title": "Learn React",
  "description": "Nothing",
  "targetDate": "2021-04-17T09:14:00.000Z"
}

###

PUT http://192.168.0.101:7000/tasks
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.bmFnZXNod2FyNTIx.SB5nAlANau9o8F0bfvlAnlwViEIggiRtimFm4FOkBAU
Content-Type: application/json

{
  "title": "Learn React Dev",
  "description": "Nothing",
  "id": "fbf14187-d372-44f1-b693-9ceae1a3bdd2"
}

###